translated 01-migrating into japanease
svelte-jp/kit pull request #32
Opened 2021-12-30 09:01 UTC by myLifeAsaDog

#24

2021-12-30 13:59 UTC, tomoam requested changes
ご対応ありがとうございます。
大変お手数なのですが、1点だけ修正をお願いできますでしょうか。

2021-12-30 13:59 UTC, tomoam commented on documentation/migrating/01-migrating.md
> +title: Sapperからの移行
titleについては翻訳しないで大丈夫です。
SvelteKitのサイトでは見出しになる要素が変更されてそれを参照する箇所と整合性が合わなくなると、 `sveltejs/site`(日本語版では`svelte-jp/site`)のビルド時にエラーになってしまうからです。
（詳しく情報共有できていなくてすみません）

2021-12-30 15:14 UTC, myLifeAsaDog commented on documentation/migrating/01-migrating.md
> +title: Sapperからの移行
すいません、タイトル戻しました！

2021-12-31 13:39 UTC, tomoam approved these changes
ありがとうございます、マージさせていただきます！

2021-12-31 13:39 UTC, merged